use eframe::egui;

/// Map egui Key to Ctrl+key byte (0x01-0x1A)
pub fn key_to_ctrl_byte(key: &egui::Key) -> Option<u8> {
    match key {
        egui::Key::A => Some(0x01),
        egui::Key::B => Some(0x02),
        egui::Key::C => Some(0x03),
        egui::Key::D => Some(0x04),
        egui::Key::E => Some(0x05),
        egui::Key::F => Some(0x06),
        egui::Key::G => Some(0x07),
        egui::Key::H => Some(0x08),
        egui::Key::I => Some(0x09),
        egui::Key::J => Some(0x0A),
        egui::Key::K => Some(0x0B),
        egui::Key::L => Some(0x0C),
        egui::Key::M => Some(0x0D),
        egui::Key::N => Some(0x0E),
        egui::Key::O => Some(0x0F),
        egui::Key::P => Some(0x10),
        egui::Key::Q => Some(0x11),
        egui::Key::R => Some(0x12),
        egui::Key::S => Some(0x13),
        egui::Key::T => Some(0x14),
        egui::Key::U => Some(0x15),
        egui::Key::V => Some(0x16),
        egui::Key::W => Some(0x17),
        egui::Key::X => Some(0x18),
        egui::Key::Y => Some(0x19),
        egui::Key::Z => Some(0x1A),
        _ => None,
    }
}

/// Map egui Key to printable character (fallback when Event::Text is missing)
pub fn key_to_char(key: &egui::Key, shift: bool) -> Option<char> {
    match key {
        // Letters
        egui::Key::A => Some(if shift { 'A' } else { 'a' }),
        egui::Key::B => Some(if shift { 'B' } else { 'b' }),
        egui::Key::C => Some(if shift { 'C' } else { 'c' }),
        egui::Key::D => Some(if shift { 'D' } else { 'd' }),
        egui::Key::E => Some(if shift { 'E' } else { 'e' }),
        egui::Key::F => Some(if shift { 'F' } else { 'f' }),
        egui::Key::G => Some(if shift { 'G' } else { 'g' }),
        egui::Key::H => Some(if shift { 'H' } else { 'h' }),
        egui::Key::I => Some(if shift { 'I' } else { 'i' }),
        egui::Key::J => Some(if shift { 'J' } else { 'j' }),
        egui::Key::K => Some(if shift { 'K' } else { 'k' }),
        egui::Key::L => Some(if shift { 'L' } else { 'l' }),
        egui::Key::M => Some(if shift { 'M' } else { 'm' }),
        egui::Key::N => Some(if shift { 'N' } else { 'n' }),
        egui::Key::O => Some(if shift { 'O' } else { 'o' }),
        egui::Key::P => Some(if shift { 'P' } else { 'p' }),
        egui::Key::Q => Some(if shift { 'Q' } else { 'q' }),
        egui::Key::R => Some(if shift { 'R' } else { 'r' }),
        egui::Key::S => Some(if shift { 'S' } else { 's' }),
        egui::Key::T => Some(if shift { 'T' } else { 't' }),
        egui::Key::U => Some(if shift { 'U' } else { 'u' }),
        egui::Key::V => Some(if shift { 'V' } else { 'v' }),
        egui::Key::W => Some(if shift { 'W' } else { 'w' }),
        egui::Key::X => Some(if shift { 'X' } else { 'x' }),
        egui::Key::Y => Some(if shift { 'Y' } else { 'y' }),
        egui::Key::Z => Some(if shift { 'Z' } else { 'z' }),
        // Numbers
        egui::Key::Num0 => Some(if shift { ')' } else { '0' }),
        egui::Key::Num1 => Some(if shift { '!' } else { '1' }),
        egui::Key::Num2 => Some(if shift { '@' } else { '2' }),
        egui::Key::Num3 => Some(if shift { '#' } else { '3' }),
        egui::Key::Num4 => Some(if shift { '$' } else { '4' }),
        egui::Key::Num5 => Some(if shift { '%' } else { '5' }),
        egui::Key::Num6 => Some(if shift { '^' } else { '6' }),
        egui::Key::Num7 => Some(if shift { '&' } else { '7' }),
        egui::Key::Num8 => Some(if shift { '*' } else { '8' }),
        egui::Key::Num9 => Some(if shift { '(' } else { '9' }),
        // Punctuation
        egui::Key::Space => Some(' '),
        egui::Key::Minus => Some(if shift { '_' } else { '-' }),
        egui::Key::Plus => Some('+'),
        egui::Key::Equals => Some(if shift { '+' } else { '=' }),
        egui::Key::OpenBracket => Some(if shift { '{' } else { '[' }),
        egui::Key::CloseBracket => Some(if shift { '}' } else { ']' }),
        egui::Key::Backslash => Some(if shift { '|' } else { '\\' }),
        egui::Key::Semicolon => Some(if shift { ':' } else { ';' }),
        egui::Key::Colon => Some(':'),
        egui::Key::Quote => Some(if shift { '"' } else { '\'' }),
        egui::Key::Comma => Some(if shift { '<' } else { ',' }),
        egui::Key::Period => Some(if shift { '>' } else { '.' }),
        egui::Key::Slash => Some(if shift { '?' } else { '/' }),
        egui::Key::Backtick => Some(if shift { '~' } else { '`' }),
        egui::Key::Pipe => Some('|'),
        egui::Key::Questionmark => Some('?'),
        _ => None,
    }
}
